import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "../providers/NextAuthProvider";


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

const roboto = Roboto({
  subsets: ["latin"],
})
export const metadata = {
  title: "Shop ease with Shop Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <NextAuthProvider>
           {children}
           </NextAuthProvider>
      </body>
    </html>
  );
}
